using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Novit.Web.Api.Data;
using Novit.Web.Api.Data.Entities;
using Novit.Web.Api.Filters;
using Novit.Web.Api.Models;
using Novit.Web.Api.Services;
using Microsoft.Extensions.Options;

namespace Novit.Web.Api.Controllers;

/// <summary>
/// Debug/test endpoints for the nurturing newsletter system.
/// Protected by API key — requires <c>X-Api-Key</c> header.
/// </summary>
[ApiController]
[Route("api/nurturing")]
[RequireApiKey]
public sealed class NurturingController(
    INurturingMailService mailService,
    IPipedriveService pipedrive,
    IAgentClient agentClient,
    IOptions<NurturingOptions> nurturingOptions,
    NovitDbContext db,
    IServiceScopeFactory scopeFactory,
    ILogger<NurturingController> logger) : ControllerBase
{
    // ── Background send status tracking ─────────────────────────────
    private static volatile SendStatus? _activeSend;

    private sealed class SendStatus
    {
        public string MonthKey { get; init; } = "";
        public int Version { get; init; }
        public string Subject { get; init; } = "";
        public int TotalRecipients { get; init; }
        public int AiClosings { get; set; }
        public int TemplateClosings => TotalRecipients - AiClosings;
        public int Sent { get; set; }
        public int Failed { get; set; }
        public bool IsComplete { get; set; }
        public bool MarkedAsSent { get; set; }
        public DateTimeOffset StartedAt { get; init; } = DateTimeOffset.UtcNow;
        public DateTimeOffset? CompletedAt { get; set; }
        public string? Error { get; set; }
    }

    /// <summary>
    /// Triggers newsletter generation with real web search and returns the result as JSON.
    /// No emails are sent — this is purely for previewing the generated content.
    /// When NURTURING_V2_ENABLED, delegates to the Python agent service.
    /// </summary>
    [HttpPost("test-generate")]
    public async Task<IActionResult> TestGenerate(CancellationToken ct)
    {
        logger.LogInformation("Delegating newsletter generation to Python agent");
        var result = await agentClient.GenerateNewsletterAsync(ct);
        if (result is null)
            return StatusCode(502, new { error = "Python agent did not respond or failed to generate newsletter." });

        var fullHtml = NurturingContentRenderer.WrapInHtmlEmail(result.Body);
        return Ok(new
        {
            subject = result.Subject,
            body = result.Body,
            fullHtml,
            reportTitle = result.ReportTitle,
            executiveSummary = result.ExecutiveSummary,
            artifactJson = result.ArtifactJson,
            generatedAt = DateTimeOffset.UtcNow,
            source = "python-agent",
            note = "This is a preview only — no emails were sent. Generated by Python agent."
        });
    }

    /// <summary>
    /// Returns the list of Pipedrive deals in the "Nurturing Automático" stage
    /// together with their contact emails. No emails are sent.
    /// </summary>
    [HttpGet("test-contacts")]
    public async Task<IActionResult> TestContacts(CancellationToken ct)
    {
        if (!pipedrive.IsConfigured)
        {
            return BadRequest(new { error = "Pipedrive is not configured (Pipedrive:PipedriveKey / PipedriveBaseUrl)." });
        }

        logger.LogInformation("Fetching nurturing deal contacts from Pipedrive via test endpoint");

        try
        {
            var contacts = await pipedrive.GetNurturingDealContactsAsync(ct);

            return Ok(new
            {
                totalContacts = contacts.Count,
                uniqueEmails = contacts.Select(c => c.ContactEmail).Distinct().Count(),
                contacts = contacts.Select(c => new
                {
                    dealId = c.DealId,
                    dealTitle = c.DealTitle,
                    contactName = c.ContactName,
                    contactEmail = c.ContactEmail,
                    organizationName = c.OrganizationName
                }),
                note = "This is a read-only query — no emails were sent."
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to fetch nurturing contacts from Pipedrive");
            return StatusCode(500, new { error = "Failed to fetch contacts.", detail = ex.Message });
        }
    }

    /// <summary>
    /// Previews the personalized greeting and closing that each Pipedrive contact would receive.
    /// Reads the latest newsletter from the database for subject + body context.
    /// When AI is configured, generates AI-powered closings for contacts with deal history.
    /// Falls back to template-based closings otherwise. No emails are sent.
    /// Optional query parameters:
    /// - <c>?ai=true</c> to enable AI closings (default: template only)
    /// - <c>?dealIds=19&dealIds=20</c> to preview only specific deals
    /// - <c>?limit=10</c> to cap the preview size
    /// </summary>
    [HttpGet("test-personalization")]
    public async Task<IActionResult> TestPersonalization(
        [FromQuery] bool ai = false,
        [FromQuery] int[]? dealIds = null,
        [FromQuery] int? limit = null,
        CancellationToken ct = default)
    {
        if (!pipedrive.IsConfigured)
            return BadRequest(new { error = "Pipedrive is not configured." });

        try
        {
            // Read latest newsletter from DB for subject + body context
            var latestNewsletter = await db.NurturingEmails
                .OrderByDescending(e => e.CreatedAt)
                .FirstOrDefaultAsync(ct);

            var newsletterSubject = latestNewsletter?.Subject ?? "Novedades tech del mes";
            var newsletterBody = latestNewsletter?.Body;

            var contacts = await pipedrive.GetNurturingDealContactsAsync(ct);

            var requestedDealIds = (dealIds ?? [])
                .Where(dealId => dealId > 0)
                .Distinct()
                .ToList();

            if (requestedDealIds.Count > 0)
            {
                var requestedDealIdSet = requestedDealIds.ToHashSet();
                var selected = contacts
                    .Where(c => requestedDealIdSet.Contains(c.DealId))
                    .ToList();

                var foundDealIds = selected
                    .Select(c => c.DealId)
                    .Distinct()
                    .ToHashSet();

                foreach (var missingDealId in requestedDealIds.Where(dealId => !foundDealIds.Contains(dealId)))
                {
                    var directContact = await pipedrive.GetDealContactAsync(missingDealId, ct);
                    if (directContact is not null)
                        selected.Add(directContact);
                }

                contacts = selected;
            }

            // Deduplicate by email
            IEnumerable<PipedriveDealContact> filtered = contacts
                .Where(c => !string.IsNullOrWhiteSpace(c.ContactEmail))
                .GroupBy(c => c.ContactEmail, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First());

            if (limit.HasValue && limit.Value > 0)
                filtered = filtered.Take(limit.Value);

            var unique = filtered.ToList();

            var useAI = ai && agentClient.IsConfigured;

            var previews = new List<object>();
            foreach (var c in unique)
            {
                var firstName = NurturingWorkflowSupport.ExtractFirstName(c.ContactName);
                var templateClosing = NurturingWorkflowSupport.BuildPersonalClosing(firstName, c.OrganizationName);
                var greeting = string.IsNullOrWhiteSpace(firstName) ? "Hola," : $"Hola {firstName},";

                string? aiClosing = null;
                List<string>? dealContext = null;

                if (useAI)
                {
                    dealContext = await pipedrive.GetDealPersonalizationContextAsync(c.DealId, ct);
                    if (dealContext.Count > 0)
                    {
                        aiClosing = await agentClient.GenerateClosingAsync(
                            newsletterSubject, newsletterBody, firstName, c.OrganizationName, dealContext, ct);
                    }
                }

                previews.Add(new
                {
                    dealId = c.DealId,
                    contactName = c.ContactName,
                    contactEmail = c.ContactEmail,
                    organizationName = c.OrganizationName,
                    firstName,
                    greeting,
                    closingUsed = aiClosing ?? templateClosing,
                    closingSource = aiClosing is not null ? "ai" : "template",
                    templateClosing,
                    aiClosing,
                    dealContextCount = dealContext?.Count,
                    dealContext,
                    dealTitle = c.DealTitle
                });
            }

            var aiCount = previews.Count(p => ((dynamic)p).closingSource == "ai");

            return Ok(new
            {
                totalContacts = previews.Count,
                requestedDealIds = requestedDealIds.Count > 0 ? requestedDealIds : null,
                limitApplied = limit,
                withName = unique.Count(c => c.ContactName is not null),
                withOrg = unique.Count(c => c.OrganizationName is not null),
                aiClosingsGenerated = useAI ? aiCount : (int?)null,
                templateFallbacks = useAI ? previews.Count - aiCount : (int?)null,
                mode = useAI ? "ai+template" : "template-only",
                newsletterSubject,
                newsletterMonthKey = latestNewsletter?.MonthKey,
                previews,
                note = useAI
                    ? "AI closings generated via GPT-4o using newsletter body context. No emails sent."
                    : "Template-only mode. Add ?ai=true to enable AI closings (uses GPT-4o). No emails sent."
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to preview personalization");
            return StatusCode(500, new { error = "Failed to fetch contacts.", detail = ex.Message });
        }
    }

    /// <summary>
    /// Generates a newsletter and sends it to reviewers for validation, exactly like the
    /// scheduled Monday flow. Saves the newsletter to the database and sends HTML preview
    /// emails to the configured reviewer list.
    /// Delegates generation to the Python agent service.
    /// </summary>
    [HttpPost("trigger-review")]
    public async Task<IActionResult> TriggerReview(CancellationToken ct)
    {
        if (!mailService.IsConfigured)
            return BadRequest(new { error = "Mail service (IMAP/SMTP) is not configured." });

        var options = nurturingOptions.Value;
        var reviewers = options.GetReviewerList();
        if (reviewers.Count == 0)
            return BadRequest(new { error = "No reviewer emails configured (Nurturing:ReviewerEmails)." });

        logger.LogInformation("Delegating trigger-review newsletter generation to Python agent");
        var agentResult = await agentClient.GenerateNewsletterAsync(ct);
        if (agentResult is null)
            return StatusCode(502, new { error = "Python agent did not respond or failed to generate newsletter." });
        var newsletter = agentResult;

        string? slidesUrl = null;
        string? slidesError = null;
        if (!string.IsNullOrWhiteSpace(newsletter.ArtifactJson))
        {
            try
            {
                using var artifactDoc = JsonDocument.Parse(newsletter.ArtifactJson);
                slidesUrl = artifactDoc.RootElement.TryGetProperty("slides_url", out var slidesUrlElement)
                    ? slidesUrlElement.GetString()
                    : null;
                slidesError = artifactDoc.RootElement.TryGetProperty("slides_error", out var slidesErrorElement)
                    ? slidesErrorElement.GetString()
                    : null;
            }
            catch (JsonException ex)
            {
                logger.LogWarning(ex, "Could not parse artifact_json returned by agent during trigger-review");
            }
        }

        try
        {
            var buenosAires = TimeZoneInfo.FindSystemTimeZoneById("America/Buenos_Aires");
            var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, buenosAires);
            var today = DateOnly.FromDateTime(now);
            var cycleResolution = await ResolveNextCycleForDraftAsync(today, ct);
            if (cycleResolution is null)
                return BadRequest(new { error = "Could not determine the next newsletter cycle." });

            var (cycle, existing) = cycleResolution.Value;
            var monthKey = cycle.CycleKey;

            if (existing is not null)
            {
                // Update existing draft and reset send state so feedback loop works
                existing.Subject = newsletter.Subject;
                existing.Body = newsletter.Body;
                existing.ReportTitle = newsletter.ReportTitle;
                existing.ExecutiveSummary = newsletter.ExecutiveSummary;
                existing.ArtifactJson = newsletter.ArtifactJson;
                existing.Version++;
                existing.IsSent = false;
                existing.IsOnHold = false;
                existing.SentAt = null;
            }
            else
            {
                // Create new entry
                // 11 AM Buenos Aires = 14:00 UTC (UTC-3)
                var scheduledSend = new DateTimeOffset(cycle.SendDate.Year, cycle.SendDate.Month, cycle.SendDate.Day,
                    14, 0, 0, TimeSpan.Zero);

                db.NurturingEmails.Add(new NurturingEmailEntity
                {
                    MonthKey = monthKey,
                    Subject = newsletter.Subject,
                    Body = newsletter.Body,
                    ReportTitle = newsletter.ReportTitle,
                    ExecutiveSummary = newsletter.ExecutiveSummary,
                    ArtifactJson = newsletter.ArtifactJson,
                    ScheduledSendDate = scheduledSend,
                    IsSent = false,
                    Version = 1
                });
            }

            await db.SaveChangesAsync(ct);

            // Send HTML preview to reviewers — the mail itself IS the preview
            var version = existing?.Version ?? 1;
            var reviewSubject = $"[REVISIÓN v{version}] {newsletter.Subject}";

            // Prepend a short reviewer note inside the same email wrapper
            var reviewNote = """
                <p style="background:#fffde7;padding:10px 14px;border-left:3px solid #f9a825;font-size:13px;color:#555;margin-bottom:20px;">
                <b>Nota para revisores:</b> Este es el mail que recibirían los contactos. Respondé con correcciones o comentarios.<br><br>
                <b>⏸ Para suspender el envío</b>, respondé con <b>"NO ENVIAR"</b> y el newsletter quedará en standby hasta nuevo aviso.
                </p>
                """;
            var slidesNote = !string.IsNullOrWhiteSpace(slidesUrl)
                ? $"<p style=\"margin:0 0 18px 0;padding:12px 14px;background:#eef5ff;border:1px solid #c9dcff;border-radius:10px;font-size:13px;color:#1f2430;\"><b>Deck de apoyo:</b> <a href=\"{WebUtility.HtmlEncode(slidesUrl)}\" style=\"color:#0A0089;font-weight:700;\">Abrir Google Slides</a></p>"
                : !string.IsNullOrWhiteSpace(slidesError)
                    ? $"<p style=\"margin:0 0 18px 0;padding:12px 14px;background:#fff4f4;border:1px solid #f3c7c7;border-radius:10px;font-size:13px;color:#7a1f1f;\"><b>Deck no disponible:</b> {WebUtility.HtmlEncode(slidesError)}</p>"
                    : string.Empty;
            var reviewWrapped = NurturingContentRenderer.WrapInHtmlEmail(reviewNote + slidesNote + newsletter.Body);

            await mailService.SendBulkEmailAsync(reviewers, reviewSubject, reviewWrapped, isHtml: true, ct: ct);

            logger.LogInformation("Newsletter v{Version} for {MonthKey} generated and sent to {Count} reviewers",
                version, monthKey, reviewers.Count);

            return Ok(new
            {
                subject = newsletter.Subject,
                bodyHtml = newsletter.Body,
                version,
                monthKey,
                reportTitle = newsletter.ReportTitle,
                executiveSummary = newsletter.ExecutiveSummary,
                artifactJson = newsletter.ArtifactJson,
                slidesUrl,
                slidesError,
                scheduledSendDate = new DateTimeOffset(cycle.SendDate.Year, cycle.SendDate.Month, cycle.SendDate.Day, 14, 0, 0, TimeSpan.Zero),
                reviewersSentTo = reviewers,
                generatedAt = DateTimeOffset.UtcNow,
                note = "Newsletter generated, saved, and sent to reviewers for validation."
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Trigger-review failed");
            return StatusCode(500, new
            {
                error = "Failed to generate/send newsletter.",
                detail = ex.Message,
                innerDetail = ex.InnerException?.Message
            });
        }
    }

    // ── Manual trigger endpoints ────────────────────────────────────

    /// <summary>
    /// Forces a check for reviewer feedback on the next pending newsletter cycle.
    /// Mirrors the scheduled validation-window flow: detects hold/resume/revision requests,
    /// revises the newsletter with AI if needed, and resends to reviewers.
    /// </summary>
    [HttpPost("trigger-check-feedback")]
    public async Task<IActionResult> TriggerCheckFeedback(CancellationToken ct)
    {
        if (!mailService.IsConfigured)
            return BadRequest(new { error = "Mail service (IMAP/SMTP) is not configured." });

        var options = nurturingOptions.Value;

        logger.LogInformation("Manual trigger-check-feedback requested via endpoint");

        try
        {
            var buenosAires = TimeZoneInfo.FindSystemTimeZoneById("America/Buenos_Aires");
            var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, buenosAires);
            var today = DateOnly.FromDateTime(now);
            var cycleResolution = await ResolveNextPendingCycleAsync(today, ct);
            if (cycleResolution is null)
                return NotFound(new { error = "No pending newsletter cycle found." });

            var (cycle, newsletter) = cycleResolution.Value;
            var monthKey = cycle.CycleKey;

            if (newsletter is null)
                return NotFound(new { error = $"No unsent newsletter found for {monthKey}." });

            // Fetch replies from reviewers
            var reviewers = options.GetReviewerList();
            var reviewerSet = new HashSet<string>(reviewers, StringComparer.OrdinalIgnoreCase);
            var unanswered = await mailService.GetUnansweredRepliesAsync(7, ct);

            var feedbackEmails = unanswered
                .Where(e => reviewerSet.Contains(e.From) &&
                            e.Subject.Contains("REVISIÓN", StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (feedbackEmails.Count == 0)
                return Ok(new
                {
                    monthKey,
                    version = newsletter.Version,
                    isOnHold = newsletter.IsOnHold,
                    feedbackFound = 0,
                    action = "none",
                    note = "No reviewer feedback found. Newsletter unchanged."
                });

            // Classify feedback
            var holdEmails = feedbackEmails.Where(e => NurturingWorkflowSupport.IsHoldRequest(e.Body)).ToList();
            var resumeEmails = feedbackEmails.Where(e => NurturingWorkflowSupport.IsResumeRequest(e.Body)).ToList();
            var revisionEmails = feedbackEmails.Except(holdEmails).Except(resumeEmails).ToList();

            // Process hold
            if (holdEmails.Count > 0)
            {
                newsletter.IsOnHold = true;
                await db.SaveChangesAsync(ct);

                var holdWrapped = NurturingContentRenderer.WrapInHtmlEmail(
                    "<p style=\"background:#ffebee;padding:10px 14px;border-left:3px solid #e53935;font-size:13px;color:#555;margin-bottom:20px;\"><b>⏸ Newsletter en standby</b><br>" +
                    $"Solicitado por: {string.Join(", ", holdEmails.Select(e => e.From))}<br>" +
                    "Respondé con <b>\"REANUDAR\"</b> o <b>\"ENVIAR\"</b> para retomar el envío.</p>" + newsletter.Body);
                await mailService.SendBulkEmailAsync(reviewers, $"[⏸ EN ESPERA] {newsletter.Subject}", holdWrapped, isHtml: true, ct: ct);

                return Ok(new { monthKey, version = newsletter.Version, action = "hold", holdRequestsFrom = holdEmails.Select(e => e.From) });
            }

            // Process resume
            if (resumeEmails.Count > 0 && newsletter.IsOnHold)
            {
                newsletter.IsOnHold = false;
                await db.SaveChangesAsync(ct);

                await mailService.SendBulkEmailAsync(reviewers, $"[✅ REANUDADO] {newsletter.Subject}",
                    NurturingContentRenderer.WrapInHtmlEmail(
                        "<p style=\"background:#e8f5e9;padding:10px 14px;border-left:3px solid #43a047;font-size:13px;color:#555;margin-bottom:20px;\"><b>✅ Newsletter reanudado</b><br>" +
                        $"Reactivado por: {string.Join(", ", resumeEmails.Select(e => e.From))}</p>" + newsletter.Body),
                    isHtml: true, ct: ct);

                return Ok(new { monthKey, version = newsletter.Version, action = "resumed", resumeRequestsFrom = resumeEmails.Select(e => e.From) });
            }

            // Process revisions
            if (revisionEmails.Count > 0)
            {
                var combinedFeedback = string.Join("\n\n---\n\n",
                    revisionEmails.Select(e => $"De {e.From}:\n{e.Body}"));

                logger.LogInformation("Delegating newsletter revision to Python agent");
                var agentRevision = await agentClient.ReviseNewsletterAsync(
                    newsletter.Subject, newsletter.Body, combinedFeedback, ct);
                if (agentRevision is null)
                {
                    return StatusCode(502, new
                    {
                        error = "Python agent did not respond or failed to revise newsletter.",
                        monthKey,
                        version = newsletter.Version,
                    });
                }

                var revised = agentRevision;

                newsletter.Subject = revised.Subject;
                newsletter.Body = revised.Body;
                newsletter.ReportTitle = revised.ReportTitle;
                newsletter.ExecutiveSummary = revised.ExecutiveSummary;
                newsletter.ArtifactJson = revised.ArtifactJson;
                newsletter.Version++;
                await db.SaveChangesAsync(ct);

                // Resend revised version to reviewers
                var reviewNote = $"""
                    <p style="background:#fffde7;padding:10px 14px;border-left:3px solid #f9a825;font-size:13px;color:#555;margin-bottom:20px;">
                    <b>Nota para revisores:</b> Versión <b>{newsletter.Version}</b> corregida según el feedback.
                    Se envía el <b>{cycle.SendDate:dd/MM/yyyy}</b> si no hay más correcciones.<br><br>
                    <b>⏸ Para suspender el envío</b>, respondé con <b>"NO ENVIAR"</b>.
                    </p>
                    """;
                var reviewWrapped = NurturingContentRenderer.WrapInHtmlEmail(reviewNote + revised.Body);
                await mailService.SendBulkEmailAsync(reviewers, $"[REVISIÓN v{newsletter.Version}] {revised.Subject}", reviewWrapped, isHtml: true, ct: ct);

                return Ok(new
                {
                    monthKey,
                    version = newsletter.Version,
                    action = "revised",
                    feedbackFrom = revisionEmails.Select(e => e.From),
                    newSubject = revised.Subject,
                    note = $"Newsletter revised to v{newsletter.Version} and resent to reviewers."
                });
            }

            return Ok(new { monthKey, version = newsletter.Version, action = "none", feedbackFound = feedbackEmails.Count,
                note = "Feedback found but no actionable changes were applied." });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Trigger-check-feedback failed");
            return StatusCode(500, new { error = "Failed to check feedback.", detail = ex.Message });
        }
    }

    /// <summary>
    /// Forces sending the next pending newsletter cycle to leads, exactly like the scheduled
    /// send flow. Includes AI-personalized closings when possible.
    /// Respects the on-hold flag unless <c>?force=true</c> is passed.
    /// Use <c>?limit=N</c> to send to only N recipients (useful for testing).
    /// Use <c>?offset=N</c> to skip the first N recipients (pagination).
    /// Use <c>?dealId=N</c> to send only to the contact of a specific Pipedrive deal.
    ///
    /// <b>Production mode</b> (no limit/offset/dealId): launches the send in background
    /// and returns immediately. Use <c>GET trigger-send/status</c> to check progress.
    /// <b>Test mode</b> (with limit/offset/dealId): sends synchronously and returns results.
    /// </summary>
    [HttpPost("trigger-send")]
    public async Task<IActionResult> TriggerSend(
        [FromQuery] bool force = false,
        [FromQuery] int? limit = null,
        [FromQuery] int? offset = null,
        [FromQuery] int? dealId = null,
        CancellationToken ct = default)
    {
        if (!mailService.IsConfigured)
            return BadRequest(new { error = "Mail service (IMAP/SMTP) is not configured." });

        var options = nurturingOptions.Value;

        logger.LogInformation("Manual trigger-send requested via endpoint (force={Force})", force);

        try
        {
            var buenosAires = TimeZoneInfo.FindSystemTimeZoneById("America/Buenos_Aires");
            var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, buenosAires);
            var today = DateOnly.FromDateTime(now);
            var cycleResolution = await ResolveNextPendingCycleAsync(today, ct);
            if (cycleResolution is null)
                return NotFound(new { error = "No pending newsletter cycle found." });

            var (cycle, newsletter) = cycleResolution.Value;
            var monthKey = cycle.CycleKey;

            if (newsletter is null)
                return NotFound(new { error = $"No unsent newsletter found for {monthKey}." });

            if (newsletter.IsOnHold && !force)
                return Conflict(new
                {
                    error = $"Newsletter {monthKey} is ON HOLD. A reviewer must reply \"REANUDAR\" or pass ?force=true to override.",
                    monthKey,
                    version = newsletter.Version,
                    isOnHold = true
                });

            // Get recipients
            var allRecipients = await GetRecipientsAsync(options, ct);
            if (allRecipients.Count == 0)
                return BadRequest(new { error = "No recipients found (check RecipientOverride or Pipedrive nurturing stage)." });

            // Filter by dealId if provided
            if (dealId.HasValue)
            {
                allRecipients = allRecipients.Where(c => c.DealId == dealId.Value).ToList();
                if (allRecipients.Count == 0)
                {
                    // Deal not in nurturing stage — fetch it directly from Pipedrive (any stage/status)
                    var directContact = await pipedrive.GetDealContactAsync(dealId.Value, ct);
                    if (directContact is null)
                        return NotFound(new { error = $"No recipient found for dealId={dealId.Value} (not found or has no contact email)." });
                    allRecipients = [directContact];
                }
                logger.LogInformation("Filtered by dealId={DealId}: {Count} recipient(s)", dealId.Value, allRecipients.Count);
            }

            // Apply offset + limit (useful for paginated testing)
            IEnumerable<PipedriveDealContact> filtered = allRecipients;
            if (offset.HasValue && offset.Value > 0)
                filtered = filtered.Skip(offset.Value);
            if (limit.HasValue && limit.Value > 0)
                filtered = filtered.Take(limit.Value);
            var recipients = filtered.ToList();

            if (recipients.Count == 0)
                return BadRequest(new { error = $"No recipients after applying offset={offset} limit={limit}. Total available: {allRecipients.Count}." });

            var isSubset = limit.HasValue || offset.HasValue;

            // ── Sync mode: only for single-deal sends (quick, one email) ──
            if (dealId.HasValue)
            {
                logger.LogInformation("Sync mode (dealId={DealId}): sending to {Count} recipient(s)",
                    dealId.Value, recipients.Count);
                return await SendSynchronousAsync(newsletter, recipients, allRecipients.Count, options, offset, limit, dealId, ct);
            }

            // ── Background mode: fire-and-forget for bulk sends ──
            if (_activeSend is { IsComplete: false })
            {
                return Conflict(new
                {
                    error = "A background send is already in progress.",
                    monthKey = _activeSend.MonthKey,
                    sent = _activeSend.Sent,
                    total = _activeSend.TotalRecipients,
                    startedAt = _activeSend.StartedAt,
                    note = "Use GET trigger-send/status to check progress."
                });
            }

            var status = new SendStatus
            {
                MonthKey = monthKey,
                Version = newsletter.Version,
                Subject = newsletter.Subject,
                TotalRecipients = recipients.Count,
            };
            _activeSend = status;

            // Capture newsletter data before scope ends
            var newsletterSubject = newsletter.Subject;
            var newsletterBody = newsletter.Body;
            var newsletterMonthKey = newsletter.MonthKey;
            var recipientOverride = options.RecipientOverride;
            var capturedRecipients = recipients.ToList();

            logger.LogInformation("Launching background send for {MonthKey} v{Version} to {Count} recipients (subset={IsSubset})",
                monthKey, newsletter.Version, recipients.Count, isSubset);

            _ = Task.Run(() => SendInBackgroundAsync(
                newsletterSubject, newsletterBody, newsletterMonthKey, newsletter.Version,
                capturedRecipients, recipientOverride, isSubset, status));

            return Accepted(new
            {
                monthKey,
                version = newsletter.Version,
                subject = newsletter.Subject,
                totalRecipients = recipients.Count,
                totalAvailable = allRecipients.Count,
                limitApplied = limit,
                offsetApplied = offset,
                isSubset,
                startedAt = status.StartedAt,
                note = $"Background send launched for {recipients.Count} recipients{(isSubset ? $" (subset of {allRecipients.Count})" : "")}. Use GET trigger-send/status to monitor progress."
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Trigger-send failed");
            return StatusCode(500, new { error = "Failed to send newsletter.", detail = ex.Message });
        }
    }

    /// <summary>
    /// Returns the status of the current or last background send.
    /// </summary>
    [HttpGet("trigger-send/status")]
    public IActionResult GetSendStatus()
    {
        if (_activeSend is null)
            return NotFound(new { error = "No background send has been triggered yet." });

        var s = _activeSend;
        return Ok(new
        {
            monthKey = s.MonthKey,
            version = s.Version,
            subject = s.Subject,
            sent = s.Sent,
            failed = s.Failed,
            totalRecipients = s.TotalRecipients,
            aiClosings = s.AiClosings,
            templateClosings = s.TemplateClosings,
            isComplete = s.IsComplete,
            markedAsSent = s.MarkedAsSent,
            startedAt = s.StartedAt,
            completedAt = s.CompletedAt,
            elapsed = (s.CompletedAt ?? DateTimeOffset.UtcNow) - s.StartedAt,
            error = s.Error,
            progress = $"{s.Sent}/{s.TotalRecipients} ({(s.TotalRecipients > 0 ? s.Sent * 100 / s.TotalRecipients : 0)}%)"
        });
    }

    /// <summary>
    /// Synchronous send for test mode (small batches with limit/offset/dealId).
    /// </summary>
    private async Task<IActionResult> SendSynchronousAsync(
        NurturingEmailEntity newsletter,
        List<PipedriveDealContact> recipients,
        int totalRecipientsCount,
        NurturingOptions options,
        int? offset, int? limit, int? dealId,
        CancellationToken ct)
    {
        // Pre-generate AI closings
        var aiClosings = new Dictionary<string, string>();
        if (agentClient.IsConfigured && pipedrive.IsConfigured)
        {
            var processedDeals = new Dictionary<int, List<string>>();
            foreach (var contact in recipients)
            {
                if (ct.IsCancellationRequested) break;
                try
                {
                    if (!processedDeals.TryGetValue(contact.DealId, out var notes))
                    {
                        notes = await pipedrive.GetDealNotesAsync(contact.DealId, ct);
                        processedDeals[contact.DealId] = notes;
                    }
                    if (notes.Count > 0)
                    {
                        var firstName = NurturingWorkflowSupport.ExtractFirstName(contact.ContactName);
                        var aiClosing = await agentClient.GenerateClosingAsync(
                            newsletter.Subject, newsletter.Body, firstName, contact.OrganizationName, notes, ct);
                        if (aiClosing is not null)
                            aiClosings[contact.ContactEmail] = aiClosing;
                    }
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to generate AI closing for {Email}", contact.ContactEmail);
                }
            }
        }

        var recipientOverride = options.RecipientOverride;
        var hasOverride = !string.IsNullOrWhiteSpace(recipientOverride);
        if (hasOverride)
            logger.LogWarning("RecipientOverride active — all emails redirect to {Override}", recipientOverride);

        var sentCount = 0;
        var isFirst = true;
        foreach (var contact in recipients)
        {
            if (ct.IsCancellationRequested) break;

            if (!isFirst)
                await Task.Delay(TimeSpan.FromSeconds(2), ct);
            isFirst = false;

            var firstName = NurturingWorkflowSupport.ExtractFirstName(contact.ContactName);
            var closing = aiClosings.TryGetValue(contact.ContactEmail, out var aiClose)
                ? aiClose
                : NurturingWorkflowSupport.BuildPersonalClosing(firstName, contact.OrganizationName);
            var personalHtml = NurturingContentRenderer.WrapInHtmlEmail(newsletter.Body, firstName, closing);

            var effectiveEmail = hasOverride ? recipientOverride! : contact.ContactEmail;
            try
            {
                await mailService.SendEmailAsync(effectiveEmail, newsletter.Subject, personalHtml, isHtml: true, ct: ct);
                sentCount++;
                if (hasOverride)
                    logger.LogInformation("Sent to {Override} (as {Contact} / {Org})", effectiveEmail, contact.ContactName, contact.OrganizationName);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to send newsletter to {Email}", contact.ContactEmail);
            }
        }

        return Ok(new
        {
            monthKey = newsletter.MonthKey,
            version = newsletter.Version,
            subject = newsletter.Subject,
            sentTo = sentCount,
            totalRecipients = totalRecipientsCount,
            offsetApplied = offset,
            limitApplied = limit,
            dealIdFilter = dealId,
            redirectedTo = hasOverride ? recipientOverride : null,
            aiClosings = aiClosings.Count,
            templateClosings = recipients.Count - aiClosings.Count,
            markedAsSent = false,
            recipients = recipients.Select(c => new { c.DealId, c.ContactName, c.ContactEmail, c.OrganizationName }),
            note = $"TEST MODE: Newsletter sent to {sentCount} recipients{(hasOverride ? $" (redirected to {recipientOverride})" : "")}. Total available: {totalRecipientsCount}. NOT marked as sent."
        });
    }

    /// <summary>
    /// Background fire-and-forget send. Runs in its own DI scope with human-like delays.
    /// </summary>
    private async Task SendInBackgroundAsync(
        string newsletterSubject, string newsletterBody, string monthKey, int version,
        List<PipedriveDealContact> recipients, string? recipientOverride, bool isSubset, SendStatus status)
    {
        await using var scope = scopeFactory.CreateAsyncScope();
        var bgLogger = scope.ServiceProvider.GetRequiredService<ILogger<NurturingController>>();
        var bgMail = scope.ServiceProvider.GetRequiredService<INurturingMailService>();
        var bgPipedrive = scope.ServiceProvider.GetRequiredService<IPipedriveService>();
        var bgDb = scope.ServiceProvider.GetRequiredService<NovitDbContext>();

        var hasOverride = !string.IsNullOrWhiteSpace(recipientOverride);

        try
        {
            bgLogger.LogInformation("▶ Background send started: {MonthKey} v{Version} → {Count} recipients",
                monthKey, version, recipients.Count);

            // Pre-generate AI closings
            var aiClosings = new Dictionary<string, string>();
            if (agentClient.IsConfigured && bgPipedrive.IsConfigured)
            {
                bgLogger.LogInformation("Pre-generating AI closings for {Count} recipients…", recipients.Count);
                var processedDeals = new Dictionary<int, List<string>>();
                foreach (var contact in recipients)
                {
                    try
                    {
                        if (!processedDeals.TryGetValue(contact.DealId, out var notes))
                        {
                            notes = await bgPipedrive.GetDealNotesAsync(contact.DealId, CancellationToken.None);
                            processedDeals[contact.DealId] = notes;
                        }
                        if (notes.Count > 0)
                        {
                            var firstName = NurturingWorkflowSupport.ExtractFirstName(contact.ContactName);
                            var aiClosing = await agentClient.GenerateClosingAsync(
                                newsletterSubject, newsletterBody, firstName, contact.OrganizationName, notes, CancellationToken.None);
                            if (aiClosing is not null)
                                aiClosings[contact.ContactEmail] = aiClosing;
                        }
                    }
                    catch (Exception ex)
                    {
                        bgLogger.LogWarning(ex, "Failed to generate AI closing for {Email}", contact.ContactEmail);
                    }
                }
                status.AiClosings = aiClosings.Count;
                bgLogger.LogInformation("AI closings: {Ai}/{Total} generated, {Template} will use template",
                    aiClosings.Count, recipients.Count, recipients.Count - aiClosings.Count);
            }

            if (hasOverride)
                bgLogger.LogWarning("RecipientOverride active — all emails redirect to {Override}", recipientOverride);

            // Send emails with human-like delays
            var isFirst = true;
            foreach (var contact in recipients)
            {
                if (!isFirst)
                {
                    var delaySec = NurturingWorkflowSupport.GetHumanLikeDelay();
                    bgLogger.LogInformation("⏳ Human-like delay: {Delay}s before next send ({Sent}/{Total})",
                        delaySec, status.Sent, recipients.Count);
                    await Task.Delay(TimeSpan.FromSeconds(delaySec));
                }
                isFirst = false;

                var firstName = NurturingWorkflowSupport.ExtractFirstName(contact.ContactName);
                var closing = aiClosings.TryGetValue(contact.ContactEmail, out var aiClose)
                    ? aiClose
                    : NurturingWorkflowSupport.BuildPersonalClosing(firstName, contact.OrganizationName);
                var personalHtml = NurturingContentRenderer.WrapInHtmlEmail(newsletterBody, firstName, closing);

                var effectiveEmail = hasOverride ? recipientOverride! : contact.ContactEmail;
                try
                {
                    await bgMail.SendEmailAsync(effectiveEmail, newsletterSubject, personalHtml, isHtml: true, ct: CancellationToken.None);
                    status.Sent++;
                    bgLogger.LogInformation("✉ [{Sent}/{Total}] Sent to {Email} ({Name} / {Org})",
                        status.Sent, recipients.Count, effectiveEmail, contact.ContactName, contact.OrganizationName);
                }
                catch (Exception ex)
                {
                    status.Failed++;
                    bgLogger.LogError(ex, "✗ Failed to send to {Email}", contact.ContactEmail);
                }
            }

            // Mark as sent only if full send (no override, no subset)
            if (!hasOverride && !isSubset)
            {
                var newsletter = await bgDb.NurturingEmails
                    .FirstOrDefaultAsync(e => e.MonthKey == monthKey && !e.IsSent);
                if (newsletter is not null)
                {
                    newsletter.IsSent = true;
                    newsletter.SentAt = DateTimeOffset.UtcNow;
                    await bgDb.SaveChangesAsync();
                    status.MarkedAsSent = true;
                    bgLogger.LogInformation("✅ Newsletter {MonthKey} marked as sent", monthKey);
                }
            }
            else
            {
                bgLogger.LogWarning("Newsletter NOT marked as sent (override={Override}, subset={Subset})",
                    hasOverride, isSubset);
            }

            status.IsComplete = true;
            status.CompletedAt = DateTimeOffset.UtcNow;
            bgLogger.LogInformation("✅ Background send complete: {Sent}/{Total} sent, {Failed} failed, elapsed {Elapsed}",
                status.Sent, recipients.Count, status.Failed, status.CompletedAt - status.StartedAt);
        }
        catch (Exception ex)
        {
            status.IsComplete = true;
            status.CompletedAt = DateTimeOffset.UtcNow;
            status.Error = ex.Message;
            bgLogger.LogError(ex, "❌ Background send failed catastrophically");
        }
    }

    /// <summary>
    /// Forces a check for unanswered lead replies and auto-responds with AI.
    /// Mirrors the daily scheduled flow: reads IMAP inbox for replies from leads,
    /// generates AI responses, sends replies, and logs to Pipedrive.
    /// </summary>
    [HttpPost("trigger-check-replies")]
    public async Task<IActionResult> TriggerCheckReplies(CancellationToken ct)
    {
        if (!mailService.IsConfigured)
            return BadRequest(new { error = "Mail service (IMAP) is not configured." });

        if (!agentClient.IsConfigured)
            return BadRequest(new { error = "Python agent is not configured for nurturing replies." });

        var options = nurturingOptions.Value;

        logger.LogInformation("Manual trigger-check-replies requested via endpoint");

        try
        {
            var unanswered = await mailService.GetUnansweredRepliesAsync(30, ct);

            // Exclude reviewer validation emails
            var reviewerSet = new HashSet<string>(options.GetReviewerList(), StringComparer.OrdinalIgnoreCase);
            var leadReplies = unanswered
                .Where(e => !(reviewerSet.Contains(e.From) &&
                              e.Subject.Contains("REVISIÓN", StringComparison.OrdinalIgnoreCase)))
                .ToList();

            if (leadReplies.Count == 0)
                return Ok(new { repliesFound = 0, repliesSent = 0, note = "No unanswered lead replies found." });

            // Build email → dealId map from Pipedrive
            var dealContactMap = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            if (pipedrive.IsConfigured)
            {
                try
                {
                    var contacts = await pipedrive.GetNurturingDealContactsAsync(ct);
                    foreach (var contact in contacts)
                        dealContactMap.TryAdd(contact.ContactEmail, contact.DealId);
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to load Pipedrive deals for note updates");
                }
            }

            // Safety filter: only respond to known Pipedrive nurturing contacts
            if (dealContactMap.Count > 0)
            {
                var knownEmails = new HashSet<string>(dealContactMap.Keys, StringComparer.OrdinalIgnoreCase);
                foreach (var reviewer in reviewerSet) knownEmails.Add(reviewer);

                leadReplies = leadReplies.Where(e => knownEmails.Contains(e.From)).ToList();
                if (leadReplies.Count == 0)
                    return Ok(new { repliesFound = unanswered.Count, repliesSent = 0, note = "Replies found but none from known Pipedrive nurturing contacts." });
            }

            // ── SAFETY FILTER 3: Only respond to emails whose subject matches a sent newsletter ──
            // Prevents auto-replying to manual conversations with the same contacts on non-nurturing topics.
            var sentNewsletterSubjects = await db.NurturingEmails
                .Where(n => n.IsSent && !string.IsNullOrEmpty(n.Subject))
                .Select(n => n.Subject)
                .ToListAsync(ct);

            if (sentNewsletterSubjects.Count > 0)
            {
                var beforeCount = leadReplies.Count;
                leadReplies = leadReplies.Where(e => IsNurturingNewsletterReply(e.Subject, sentNewsletterSubjects)).ToList();
                logger.LogInformation("Newsletter subject filter: {Before} → {After} replies", beforeCount, leadReplies.Count);

                if (leadReplies.Count == 0)
                    return Ok(new { repliesFound = unanswered.Count, repliesSent = 0, note = "Replies found but none match sent newsletter subjects." });
            }

            // Determine effective recipient: if RecipientOverride is set, redirect all replies there (testing mode)
            var recipientOverride = options.RecipientOverride;
            var hasOverride = !string.IsNullOrWhiteSpace(recipientOverride);
            if (hasOverride)
            {
                logger.LogWarning("RecipientOverride is set — all auto-replies will be redirected to {Override} instead of real senders",
                    recipientOverride);
            }

            var results = new List<object>();
            var repliedMessageIds = new List<string>();
            foreach (var email in leadReplies)
            {
                if (ct.IsCancellationRequested) break;
                try
                {
                    var senderName = email.From.Contains('@')
                        ? email.From.Split('@')[0].Replace('.', ' ').Replace('_', ' ')
                        : email.From;

                    var reply = await agentClient.GenerateReplyAsync(email.Subject, email.Body, senderName, ct);
                    if (string.IsNullOrWhiteSpace(reply))
                        throw new InvalidOperationException("Python agent did not return a reply for the lead email.");

                    // Use override recipient if configured, otherwise reply to the actual sender
                    var effectiveRecipient = hasOverride ? recipientOverride! : email.From;
                    await mailService.SendReplyAsync(effectiveRecipient, email.Subject, reply, email.MessageId, ct: ct);

                    repliedMessageIds.Add(email.MessageId);

                    // Log to Pipedrive
                    if (dealContactMap.TryGetValue(email.From, out var dealId))
                    {
                        var noteHtml = $"<b>Respuesta de nurturing — {DateTimeOffset.UtcNow:yyyy-MM-dd}</b><br><br>" +
                                       $"<b>De:</b> {WebUtility.HtmlEncode(email.From)}<br>" +
                                       $"<b>Asunto:</b> {WebUtility.HtmlEncode(email.Subject)}<br><br>" +
                                       $"<b>Mensaje del lead:</b><br>{WebUtility.HtmlEncode(email.Body).Replace("\n", "<br>")}<br><br>" +
                                       $"<b>Respuesta automática:</b><br>{WebUtility.HtmlEncode(reply).Replace("\n", "<br>")}";
                        await pipedrive.AddNoteToDealAsync(dealId, noteHtml, ct);
                    }

                    results.Add(new { from = email.From, sentTo = effectiveRecipient, subject = email.Subject, status = "replied", redirected = hasOverride, loggedToPipedrive = dealContactMap.ContainsKey(email.From) });
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "Failed to auto-reply to {From}", email.From);
                    results.Add(new { from = email.From, subject = email.Subject, status = "failed", error = ex.Message });
                }
            }

            // Mark all successfully replied emails as read
            if (repliedMessageIds.Count > 0)
            {
                try
                {
                    await mailService.MarkAsReadAsync(repliedMessageIds, ct);
                    logger.LogInformation("Marked {Count} replied emails as read", repliedMessageIds.Count);
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, "Failed to mark replied emails as read");
                }
            }

            return Ok(new
            {
                repliesFound = leadReplies.Count,
                repliesSent = results.Count(r => ((dynamic)r).status == "replied"),
                results,
                note = "Lead replies processed and auto-responded."
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Trigger-check-replies failed");
            return StatusCode(500, new { error = "Failed to check replies.", detail = ex.Message });
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────

    /// <summary>
    /// Gets newsletter recipients from Pipedrive (nurturing stage).
    /// If RecipientOverride is set AND Pipedrive is not available, falls back to override emails.
    /// The override redirect is applied at send time, not here — so personalization data is preserved.
    /// </summary>
    private async Task<List<PipedriveDealContact>> GetRecipientsAsync(NurturingOptions options, CancellationToken ct)
    {
        if (pipedrive.IsConfigured)
        {
            var contacts = await pipedrive.GetNurturingDealContactsAsync(ct);
            var unique = contacts
                .Where(c => !string.IsNullOrWhiteSpace(c.ContactEmail))
                .GroupBy(c => c.ContactEmail, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .ToList();

            if (unique.Count > 0)
                return unique;
        }

        // Fallback: if Pipedrive is not configured or returned empty, use override emails
        if (!string.IsNullOrWhiteSpace(options.RecipientOverride))
        {
            return options.RecipientOverride
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(email => new PipedriveDealContact(0, "Override", email, null, null))
                .ToList();
        }

        return [];
    }

    private async Task<(NurturingCycleSlot Cycle, NurturingEmailEntity? Newsletter)?> ResolveNextCycleForDraftAsync(
        DateOnly today,
        CancellationToken ct)
    {
        foreach (var cycle in NurturingSchedule.GetUpcomingCycles(today))
        {
            var existing = await db.NurturingEmails
                .FirstOrDefaultAsync(e => e.MonthKey == cycle.CycleKey, ct);

            if (existing is null || !existing.IsSent)
                return (cycle, existing);
        }

        return null;
    }

    private async Task<(NurturingCycleSlot Cycle, NurturingEmailEntity Newsletter)?> ResolveNextPendingCycleAsync(
        DateOnly today,
        CancellationToken ct)
    {
        foreach (var cycle in NurturingSchedule.GetUpcomingCycles(today))
        {
            var existing = await db.NurturingEmails
                .FirstOrDefaultAsync(e => e.MonthKey == cycle.CycleKey && !e.IsSent, ct);

            if (existing is not null)
                return (cycle, existing);
        }

        return null;
    }

    /// <summary>
    /// Strips Re:, Fwd:, RE:, FW: prefixes (possibly repeated/nested) from an email subject.
    /// </summary>
    private static string StripReplyPrefixes(string subject)
    {
        if (string.IsNullOrWhiteSpace(subject)) return "";
        return System.Text.RegularExpressions.Regex.Replace(
            subject.Trim(), @"^(\s*(Re|Fwd|FW|Fw)\s*:\s*)+", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase).Trim();
    }

    /// <summary>
    /// Checks whether an incoming email's subject matches a newsletter we sent.
    /// Prevents auto-replying to manual conversations with the same contacts.
    /// </summary>
    private static bool IsNurturingNewsletterReply(string emailSubject, IReadOnlyList<string> sentNewsletterSubjects)
    {
        var cleanSubject = StripReplyPrefixes(emailSubject);
        if (string.IsNullOrWhiteSpace(cleanSubject)) return false;

        return sentNewsletterSubjects.Any(ns =>
            cleanSubject.Contains(ns, StringComparison.OrdinalIgnoreCase) ||
            ns.Contains(cleanSubject, StringComparison.OrdinalIgnoreCase));
    }
}
