"""Pydantic schemas for the Community Manager agent."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, model_validator


FIXED_VIDEO_DURATION_SECONDS = 20
MIN_IMAGE_POST_IMAGES = 2
MAX_IMAGE_POST_IMAGES = 6


# ── Enums ──────────────────────────────────────────────────────────

class ContentType(str, Enum):
    IMAGE_POST = "image_post"
    TEXT_POST = "text_post"
    VIDEO_POST = "video_post"


class ImageModelChoice(str, Enum):
    IMAGE_1_5 = "image_1_5"
    IMAGE_2 = "image_2"


class ImageQuality(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class VideoTemplateChoice(str, Enum):
    STORY_EXPLAINER = "story_explainer"
    NEWS_BREAKDOWN = "news_breakdown"
    UI_WALKTHROUGH = "ui_walkthrough"
    CASE_STUDY = "case_study"
    MYTH_VS_REALITY = "myth_vs_reality"


class ReviewStage(str, Enum):
    PRE_MEDIA = "pre_media"
    FINAL = "final"


class PostStatus(str, Enum):
    PLANNED = "planned"
    DRAFT = "draft"
    EVALUATED = "evaluated"
    APPROVED = "approved"
    PUBLISHED = "published"
    REJECTED = "rejected"


class ContentTone(str, Enum):
    PROFESSIONAL = "professional"
    CASUAL = "casual"
    INSPIRATIONAL = "inspirational"
    EDUCATIONAL = "educational"
    PROMOTIONAL = "promotional"


class Platform(str, Enum):
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    TIKTOK = "tiktok"


class ReplyTargetType(str, Enum):
    DIRECT_MESSAGE = "direct_message"
    COMMENT = "comment"


# ── Strategist output ─────────────────────────────────────────────

class ContentStrategy(BaseModel):
    """Output of the Strategist node."""
    content_type: ContentType
    topic: str
    angle: str = ""
    objective: str
    target_audience: str = "General followers"
    tone: ContentTone = ContentTone.PROFESSIONAL
    key_messages: list[str] = Field(default_factory=list)
    supporting_points: list[str] = Field(default_factory=list)
    language: str = "es-AR"
    image_model: ImageModelChoice = ImageModelChoice.IMAGE_2
    image_quality: ImageQuality = ImageQuality.HIGH
    video_duration_seconds: int = Field(default=FIXED_VIDEO_DURATION_SECONDS, ge=4, le=30)
    num_images: int = Field(default=MIN_IMAGE_POST_IMAGES, ge=0)
    video_template: VideoTemplateChoice = VideoTemplateChoice.STORY_EXPLAINER
    reasoning: str = ""

    @model_validator(mode="after")
    def lock_video_duration(self):
        self.num_images = max(0, min(self.num_images, MAX_IMAGE_POST_IMAGES))
        if self.content_type == ContentType.VIDEO_POST:
            self.video_duration_seconds = FIXED_VIDEO_DURATION_SECONDS
        if self.content_type == ContentType.IMAGE_POST:
            self.num_images = max(self.num_images, MIN_IMAGE_POST_IMAGES)
        return self


# ── Copywriter output ─────────────────────────────────────────────

class PostCopy(BaseModel):
    """Text content generated by the Copywriter."""
    caption: str = ""
    hashtags: list[str] = Field(default_factory=list)
    alt_text: str = ""


# ── Designer output ────────────────────────────────────────────────

class GeneratedImage(BaseModel):
    """A single generated image."""
    prompt: str = ""
    review_summary: str = ""
    visible_text: str = ""
    slide_number: int | None = None
    local_path: str | None = None
    url: str | None = None
    blob_name: str | None = None


class PlannedVideoClip(BaseModel):
    """A single planned supporting clip inside a composite video."""
    prompt: str = ""
    purpose: str = ""
    review_summary: str = ""
    start_second: float = 0
    duration_seconds: int = 4
    transition: str = "dissolve"


class GeneratedVideo(BaseModel):
    """A generated video."""
    prompt: str = ""
    review_summary: str = ""
    avatar_script: str = ""
    supporting_clips: list[PlannedVideoClip] = Field(default_factory=list)
    avatar_intro_seconds: int = 0
    avatar_outro_seconds: int = 0
    video_template: str = VideoTemplateChoice.STORY_EXPLAINER.value
    duration_seconds: int = FIXED_VIDEO_DURATION_SECONDS
    local_path: str | None = None
    url: str | None = None
    blob_name: str | None = None
    job_id: str | None = None


class DesignerOutput(BaseModel):
    """Output of the Designer node."""
    images: list[GeneratedImage] = Field(default_factory=list)
    video: GeneratedVideo | None = None
    style_notes: str = ""


# ── Evaluator output ──────────────────────────────────────────────

class SlideReview(BaseModel):
    """Review feedback scoped to a specific carousel slide."""
    slide_number: int = Field(ge=1, le=MAX_IMAGE_POST_IMAGES)
    approved: bool = False
    feedback: str = ""
    issues: list[str] = Field(default_factory=list)


class PromptReviewResult(BaseModel):
    """Prompt-only QA result before paying for image generation."""
    approved: bool = False
    feedback: str = ""
    issues: list[str] = Field(default_factory=list)
    slide_reviews: list[SlideReview] = Field(default_factory=list)

class EvaluationResult(BaseModel):
    """Output of the Evaluator node."""
    approved: bool = False
    score: int = Field(default=0, ge=0, le=10)
    feedback: str = ""
    issues: list[str] = Field(default_factory=list)
    slide_reviews: list[SlideReview] = Field(default_factory=list)
    retry_target: str | None = None  # "copywriter" | "designer" | "abort" | None


# ── Publisher output ──────────────────────────────────────────────

class PlatformResult(BaseModel):
    """Result from publishing to a single platform."""
    platform: Platform
    success: bool = False
    post_id: str | None = None
    error: str | None = None
    permalink: str | None = None


class PublishResult(BaseModel):
    """Aggregated result from all platforms."""
    results: list[PlatformResult] = Field(default_factory=list)
    published_at: datetime | None = None

    @property
    def all_success(self) -> bool:
        return all(r.success for r in self.results) and len(self.results) > 0


# ── Incoming message (for Responder) ──────────────────────────────

class IncomingMessage(BaseModel):
    """A message received from a social media platform."""
    platform: Platform
    sender_id: str
    sender_name: str = ""
    text: str
    message_id: str = ""
    reply_target_id: str = ""
    reply_target_type: ReplyTargetType = ReplyTargetType.DIRECT_MESSAGE
    post_context_id: str = ""
    post_context_text: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)


class OutgoingReply(BaseModel):
    """Reply generated by the Responder."""
    text: str
    in_reply_to: str = ""  # message_id
    platform: Platform = Platform.INSTAGRAM


# ── Nurturing schemas ─────────────────────────────────────────────

class NewsletterContent(BaseModel):
    """Generated newsletter body + subject."""
    subject: str
    body: str
    report_title: str = ""
    executive_summary: str = ""
    artifact_json: str | None = None


class RadarInsight(BaseModel):
    """A sourced AI Radar insight block."""
    headline: str
    summary: str
    business_impact: str
    source_title: str
    source_url: str
    source_date: str = ""
    country_tag: str = ""  # "AR" | "ES" | "GLOBAL"
    category: str = ""  # taxonomía: multipolaridad, pricing, regulacion, breakthroughs, proveedores, ciberseguridad, agentes, subsidios
    # New fields for the rework: model launches & metadata
    is_model_launch: bool = False
    vendor: str = ""  # e.g. "OpenAI", "Anthropic", "Google DeepMind"
    model_name: str = ""  # e.g. "GPT-5.4", "Claude Sonnet 4.5"
    benchmark_text: str = ""  # e.g. "MMLU Pro 92.1"
    pricing_text: str = ""  # e.g. "$2.50/M input tokens"


class RadarChartItem(BaseModel):
    """A quantitative datapoint rendered in the highlighted chart."""
    label: str
    value: float
    unit: str
    source_title: str
    source_url: str


class BenchmarkEntry(BaseModel):
    """A single model in the top 5 benchmark + pricing ranking (Slide 1 tables).

    ``benchmark_name`` lets each entry cite the specific benchmark the
    score comes from. The snapshot's top-level ``BenchmarkSnapshot.benchmark_name``
    is the *preferred* benchmark (typically MMLU Pro). If a model's MMLU
    Pro score isn't public, the researcher can use GPQA Diamond, AIME
    2025, SWE-bench Verified, MATH-500, etc. as a fallback — the
    benchmark_name per entry makes the substitution transparent in the
    slide.
    """
    vendor: str = ""            # "OpenAI", "Anthropic", "Google DeepMind", "Meta", "Mistral", "DeepSeek", "Qwen", "xAI"
    model: str = ""             # "GPT-5.4", "Claude Opus 4.8", "Gemini 3.5 Flash"
    benchmark_name: str = "MMLU Pro"  # which benchmark the `score` field is on
    score: float | None = None  # benchmark score (0-100). None if not found.
    cost_per_1m_input: float | None = None   # USD per 1M input tokens
    cost_per_1m_output: float | None = None  # USD per 1M output tokens
    rank: int = 0               # 1..5 (1 = best by score in benchmark top 5)


class BenchmarkSnapshot(BaseModel):
    """Top-5 benchmark + pricing snapshot for a given month (Slide 1 charts).

    The snapshot is sorted by `score` desc within `entries`. MoM deltas are
    computed downstream by the publisher from a previous-month snapshot.

    ``source`` documents where the data came from (e.g. "artificialanalysis.io"
    for research-found data, "Precios referenciales — documentación oficial
    de cada vendor" for the fallback seed). Displayed below the charts so
    the reader can verify.
    """
    benchmark_name: str = "MMLU Pro"  # default; configurable via env var
    month_key: str = ""               # "2026-06" (set by researcher at extraction time)
    entries: list[BenchmarkEntry] = Field(default_factory=list)  # max 5
    source: str = ""                  # provenance shown below charts on slide 1


class RadarReport(BaseModel):
    """Structured AI Radar payload used to build email and Google Slides artifacts."""
    subject: str
    report_title: str
    executive_summary: str  # full version for email
    slide_summary: str = ""  # short version for slide 1 (3 bullets, max 400 chars)
    insights: list[RadarInsight] = Field(default_factory=list)  # principales (hasta 3)
    insights_secondary: list[RadarInsight] = Field(default_factory=list)  # secundarios (hasta 3)
    chart_title: str = ""
    chart_subtitle: str = ""
    chart_items: list[RadarChartItem] = Field(default_factory=list)
    discarded_insights: list[dict] = Field(default_factory=list)  # descartados con score y motivo
    conclusions: str = ""  # conclusiones especulativas para slide 4
    # Slide 2 & 3: full Markdown text generated by the writer (single textbox per slide)
    slide_2_text: str = ""  # Markdown completo para Slide AR (max 500 chars)
    slide_3_text: str = ""  # Markdown completo para Slide ES (max 500 chars)
    # Slide 1 indicator boxes (legacy string format, kept for backward compat)
    benchmark_data: str = ""  # benchmark scores of top models
    adoption_data: str = ""   # AI adoption rates (Global, ES, AR)
    pricing_data: str = ""    # cost per token of main models
    # Slide 1 ranking tables (PR B): structured top 5 benchmark + pricing
    benchmark_snapshot: BenchmarkSnapshot | None = None


class NurturingRecipient(BaseModel):
    """A recipient from the .NET internal API (Pipedrive data)."""
    deal_id: int
    deal_title: str = ""
    contact_name: str = ""
    first_name: str = ""
    email: str = ""
    org_name: str = ""


class DealNote(BaseModel):
    """A note attached to a Pipedrive deal."""
    content: str
    add_time: str = ""
